#!/bin/bash

JUJU=$SNAP/bin/juju

set -x

$JUJU destroy-controller --destroy-all-models --yes A &
$JUJU destroy-controller --destroy-all-models --yes B &
wait

$JUJU bootstrap A lxd --config enable-os-upgrade=false --upload-tools &
$JUJU bootstrap B lxd --config enable-os-upgrade=false --upload-tools &
wait

$JUJU add-model -c A --config enable-os-upgrade=false foo
$JUJU deploy -m A:foo elasticsearch-cluster
$JUJU switch A:foo
watch $JUJU status -m A:foo
